name: matrix Update

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

concurrency:
  group: scraper
  cancel-in-progress: false

jobs:

# -----------------------------
# PREPARE MATRIX
# -----------------------------

  prepare:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set.outputs.matrix }}

    steps:

      - uses: actions/checkout@v4

      - name: Generate Matrix
        id: set
        run: |

          MATRIX=$(node -e '
          const cats=require("./data/categories.json");
          console.log(JSON.stringify({
            category: cats.map(c=>c.slug)
          }));
          ')

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT


# -----------------------------
# SCRAPER
# -----------------------------

  scraper:

    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 355

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Run Scraper
        env:
          CATEGORY: ${{ matrix.category }}
        run: |

          echo "CATEGORY: $CATEGORY"

          node update5.js "$CATEGORY"

      - name: Commit Data
        run: |

          git config --global user.name "auto-bot"
          git config --global user.email "bot@github.com"

          git add data || true

          if git diff --staged --quiet
          then
            echo "no change"
          else

            git commit -m "update ${{ matrix.category }}"

            for i in {1..5}; do
              git pull --rebase origin main && git push && break
              echo "retry push"
              sleep 5
            done

          fi


# -----------------------------
# AUTO CONTINUE
# -----------------------------

  restart:

    needs: scraper
    runs-on: ubuntu-latest

    if: always()

    steps:

      - name: Trigger Next Run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo "restart workflow"

          gh workflow run matrix.yml
