name: Daily Update

on:
  schedule:
    - cron: '0 19 * * *'   # 02:00 เวลาไทย (UTC+7)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20   # 🔥 เปลี่ยนเป็น 20

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: |
          node update.js thai
          node update.js subthai
          node update.js china
          node update.js thai2
          node update.js movie
          node update.js end
          node update.js noend

      - name: Commit if changed
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "auto@bot.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update"
          git push
